/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Mascarada.Partida;
import Mascarada.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListCellRenderer;


  
/**
 *
 * @author Alumno
 */
public class Cabecera extends javax.swing.JPanel {

    private Partida partida;
    /**
     * Creates new form CabeceraImport
     */
    public Cabecera() {
        initComponents();
        barraProgreso.setForeground(Color.white);
        barraSangre.setForeground(Color.red);
        barraSospecha.setForeground(Color.blue);
        barraVida.setForeground(Color.green);
        nombre.setForeground(Color.white);
        clan.setForeground(Color.white);
        habilidad1.setForeground(Color.white);
        habilidad2.setForeground(Color.white);
        hora.setForeground(Color.white);
        horaActual.setForeground(Color.white);
        sospecha.setForeground(Color.white);
        sedSangre.setForeground(Color.white);
        progreso.setForeground(Color.white);
        tiempoJugado.setForeground(Color.white);
        tiempoJugadoDato.setForeground(Color.white);
        vida.setForeground(Color.white); 
        
        ImageIcon ImagenEscena=new javax.swing.ImageIcon(getClass().getResource(partida.getProtagonista().getClan().getImagen()));
        Image image = ImagenEscena.getImage();
        Image newimg = image.getScaledInstance( foto.getWidth(),foto.getHeight(),  java.awt.Image.SCALE_SMOOTH); 
        ImagenEscena = new ImageIcon(newimg);
        foto.setIcon(ImagenEscena);

    }

 
 
   
    




   
    


    /**
     * Inserta y muestra los datos más relevantes de una partida.
     *
     * @param partida Objeto con la información sobre una partida.
     */
    public void insertarDatosPartida(Partida partida) {
        nombre.setText(partida.getProtagonista().getNombre());
        String[] habiliades = partida.getProtagonista().getHabilidades().split(";");
        habilidad1.setText(habiliades[0]);
        habilidad2.setText(habiliades[1]);
        clan.setText(partida.getProtagonista().getClan().getNombre());
        hora.setText(partida.getFecha() + "");
        barraSangre.setValue(partida.getSedDeSangre());
        barraSangre.setMaximum(Utilidades.SED_MAX);
        barraProgreso.setValue(partida.getProgreso());
        barraProgreso.setMaximum(Utilidades.PROGRESO_MAX);
        barraSospecha.setValue(partida.getSospecha());
        barraSospecha.setMaximum(Utilidades.SOSPECHA_MAX);
        barraVida.setValue(partida.getProtagonista().getVidaActual());
        barraVida.setMaximum(partida.getProtagonista().getVidaMax());
        tiempoJugadoDato.setText(partida.getTiempo() + "");
        System.out.println(partida.getProtagonista().getClan().getImagen());
        ImageIcon imagen =  new javax.swing.ImageIcon(getClass().getResource(partida.getProtagonista().getClan().getImagen()));
        foto.setIcon(imagen);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        clan = new javax.swing.JLabel();
        habilidad1 = new javax.swing.JLabel();
        habilidad2 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        horaActual = new javax.swing.JLabel();
        sedSangre = new javax.swing.JLabel();
        barraSangre = new javax.swing.JProgressBar();
        sospecha = new javax.swing.JLabel();
        barraSospecha = new javax.swing.JProgressBar();
        vida = new javax.swing.JLabel();
        barraVida = new javax.swing.JProgressBar();
        progreso = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        tiempoJugado = new javax.swing.JLabel();
        tiempoJugadoDato = new javax.swing.JLabel();
        fondoCabecera = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        foto.setText("Foto");
        jPanel1.add(foto);
        foto.setBounds(0, 10, 210, 200);

        nombre.setText("Nombre");
        jPanel1.add(nombre);
        nombre.setBounds(270, 20, 194, 25);

        clan.setText("Clan");
        jPanel1.add(clan);
        clan.setBounds(270, 50, 194, 24);

        habilidad1.setText("Habilidad 1");
        jPanel1.add(habilidad1);
        habilidad1.setBounds(270, 80, 120, 30);

        habilidad2.setText("Habilidad 2");
        jPanel1.add(habilidad2);
        habilidad2.setBounds(270, 110, 120, 30);

        hora.setText("xx:xx");
        jPanel1.add(hora);
        hora.setBounds(330, 140, 60, 30);

        horaActual.setText("Hora:");
        jPanel1.add(horaActual);
        horaActual.setBounds(270, 140, 30, 30);

        sedSangre.setText("Sed de sangre:");
        jPanel1.add(sedSangre);
        sedSangre.setBounds(520, 20, 120, 30);

        barraSangre.setBackground(new java.awt.Color(0, 0, 0));
        barraSangre.setValue(50);
        jPanel1.add(barraSangre);
        barraSangre.setBounds(630, 20, 250, 30);

        sospecha.setText("Sospecha:");
        jPanel1.add(sospecha);
        sospecha.setBounds(520, 60, 120, 30);

        barraSospecha.setBackground(new java.awt.Color(0, 0, 0));
        barraSospecha.setValue(50);
        jPanel1.add(barraSospecha);
        barraSospecha.setBounds(630, 60, 250, 30);

        vida.setText("Vida:");
        jPanel1.add(vida);
        vida.setBounds(520, 100, 120, 30);

        barraVida.setBackground(new java.awt.Color(0, 0, 0));
        barraVida.setValue(50);
        jPanel1.add(barraVida);
        barraVida.setBounds(630, 100, 250, 30);

        progreso.setText("Progreso:");
        jPanel1.add(progreso);
        progreso.setBounds(520, 140, 120, 30);

        barraProgreso.setBackground(new java.awt.Color(0, 0, 0));
        barraProgreso.setValue(50);
        jPanel1.add(barraProgreso);
        barraProgreso.setBounds(630, 140, 250, 30);

        tiempoJugado.setText("Tiempo jugado:");
        jPanel1.add(tiempoJugado);
        tiempoJugado.setBounds(270, 170, 90, 30);

        tiempoJugadoDato.setText("xx:xx");
        jPanel1.add(tiempoJugadoDato);
        tiempoJugadoDato.setBounds(370, 170, 60, 30);

        fondoCabecera.setText("jLabel1");
        jPanel1.add(fondoCabecera);
        fondoCabecera.setBounds(-10, 0, 1000, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JProgressBar barraSangre;
    private javax.swing.JProgressBar barraSospecha;
    private javax.swing.JProgressBar barraVida;
    private javax.swing.JLabel clan;
    private javax.swing.JLabel fondoCabecera;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel habilidad1;
    private javax.swing.JLabel habilidad2;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel horaActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel progreso;
    private javax.swing.JLabel sedSangre;
    private javax.swing.JLabel sospecha;
    private javax.swing.JLabel tiempoJugado;
    private javax.swing.JLabel tiempoJugadoDato;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables

}