/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Mascarada.Partida;

/**
 *
 * @author Alumno
 */
public class Cabecera extends javax.swing.JPanel {

    private Partida partida;
    
    /**
     * Creates new form CabeceraImport
     
    public Cabecera(Partida partida) {
        initComponents();
        this.partida = partida;
        
    }
    * */
        /**
     * Creates new form CabeceraImport
     */
    public Cabecera() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        clan = new javax.swing.JLabel();
        habilidad1 = new javax.swing.JLabel();
        habilidad2 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        horaActual = new javax.swing.JLabel();
        sedSangre = new javax.swing.JLabel();
        barraSangre = new javax.swing.JProgressBar();
        sospecha = new javax.swing.JLabel();
        barraSospecha = new javax.swing.JProgressBar();
        vida = new javax.swing.JLabel();
        barraVida = new javax.swing.JProgressBar();
        progreso = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        lugarActual = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        foto.setText("Foto");
        jPanel1.add(foto);
        foto.setBounds(23, 18, 149, 128);

        nombre.setText("Nombre");
        jPanel1.add(nombre);
        nombre.setBounds(20, 160, 194, 25);

        clan.setText("Clan");
        jPanel1.add(clan);
        clan.setBounds(20, 190, 194, 24);

        habilidad1.setText("Habilidad 1");
        jPanel1.add(habilidad1);
        habilidad1.setBounds(280, 30, 120, 30);

        habilidad2.setText("Habilidad 2");
        jPanel1.add(habilidad2);
        habilidad2.setBounds(280, 90, 120, 30);

        hora.setText("xx:xx");
        jPanel1.add(hora);
        hora.setBounds(330, 140, 60, 30);

        horaActual.setText("Hora:");
        jPanel1.add(horaActual);
        horaActual.setBounds(280, 140, 30, 30);

        sedSangre.setText("Sed de sangre:");
        jPanel1.add(sedSangre);
        sedSangre.setBounds(520, 20, 120, 30);
        jPanel1.add(barraSangre);
        barraSangre.setBounds(630, 20, 250, 30);

        sospecha.setText("Sospecha:");
        jPanel1.add(sospecha);
        sospecha.setBounds(520, 60, 120, 30);
        jPanel1.add(barraSospecha);
        barraSospecha.setBounds(630, 60, 250, 30);

        vida.setText("Vida:");
        jPanel1.add(vida);
        vida.setBounds(520, 100, 120, 30);
        jPanel1.add(barraVida);
        barraVida.setBounds(630, 100, 250, 30);

        progreso.setText("Progreso3:");
        jPanel1.add(progreso);
        progreso.setBounds(520, 140, 120, 30);

        barraProgreso.setValue(50);
        jPanel1.add(barraProgreso);
        barraProgreso.setBounds(630, 140, 250, 30);

        lugarActual.setText("Lugar en el que te encuentras:");
        jPanel1.add(lugarActual);
        lugarActual.setBounds(280, 190, 600, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JProgressBar barraSangre;
    private javax.swing.JProgressBar barraSospecha;
    private javax.swing.JProgressBar barraVida;
    private javax.swing.JLabel clan;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel habilidad1;
    private javax.swing.JLabel habilidad2;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel horaActual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lugarActual;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel progreso;
    private javax.swing.JLabel sedSangre;
    private javax.swing.JLabel sospecha;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
