/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Alumno
 */
public class CargaBorrar extends javax.swing.JPanel {

    /**
     * Creates new form CabeceraImport
     */
    public CargaBorrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Foto = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Clan = new javax.swing.JLabel();
        Habilidad1 = new javax.swing.JLabel();
        Habilidad2 = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        horaActual = new javax.swing.JLabel();
        SedSangre = new javax.swing.JLabel();
        BarraSangre = new javax.swing.JProgressBar();
        Sospecha = new javax.swing.JLabel();
        BarraSospecha = new javax.swing.JProgressBar();
        Vida = new javax.swing.JLabel();
        barraVida = new javax.swing.JProgressBar();
        Progreso = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        LugarActual = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        Foto.setText("Foto");
        jPanel1.add(Foto);
        Foto.setBounds(23, 18, 149, 128);

        Nombre.setText("Nombre");
        jPanel1.add(Nombre);
        Nombre.setBounds(20, 160, 194, 25);

        Clan.setText("Clan");
        jPanel1.add(Clan);
        Clan.setBounds(20, 190, 194, 24);

        Habilidad1.setText("Habilidad 1");
        jPanel1.add(Habilidad1);
        Habilidad1.setBounds(280, 30, 120, 30);

        Habilidad2.setText("Habilidad 2");
        jPanel1.add(Habilidad2);
        Habilidad2.setBounds(280, 90, 120, 30);

        Hora.setText("xx:xx");
        jPanel1.add(Hora);
        Hora.setBounds(330, 140, 60, 30);

        horaActual.setText("Hora:");
        jPanel1.add(horaActual);
        horaActual.setBounds(280, 140, 30, 30);

        SedSangre.setText("Sed de sangre:");
        jPanel1.add(SedSangre);
        SedSangre.setBounds(520, 20, 120, 30);
        jPanel1.add(BarraSangre);
        BarraSangre.setBounds(630, 20, 250, 30);

        Sospecha.setText("Sospecha:");
        jPanel1.add(Sospecha);
        Sospecha.setBounds(520, 60, 120, 30);
        jPanel1.add(BarraSospecha);
        BarraSospecha.setBounds(630, 60, 250, 30);

        Vida.setText("Vida:");
        jPanel1.add(Vida);
        Vida.setBounds(520, 100, 120, 30);
        jPanel1.add(barraVida);
        barraVida.setBounds(630, 100, 250, 30);

        Progreso.setText("Progreso3:");
        jPanel1.add(Progreso);
        Progreso.setBounds(520, 140, 120, 30);

        barraProgreso.setValue(50);
        jPanel1.add(barraProgreso);
        barraProgreso.setBounds(630, 140, 250, 30);

        LugarActual.setText("Lugar en el que te encuentras:");
        jPanel1.add(LugarActual);
        LugarActual.setBounds(280, 190, 600, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraSangre;
    private javax.swing.JProgressBar BarraSospecha;
    private javax.swing.JLabel Clan;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Habilidad1;
    private javax.swing.JLabel Habilidad2;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel LugarActual;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Progreso;
    private javax.swing.JLabel SedSangre;
    private javax.swing.JLabel Sospecha;
    private javax.swing.JLabel Vida;
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JProgressBar barraVida;
    private javax.swing.JLabel horaActual;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
