/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JPanel;

/**
 *
 * @author Moru
 */
public class Escena_Completa extends javax.swing.JFrame {

    private JPanel footer;

    /**
     * Creates new form Eleccion_2
     */
    public Escena_Completa() {
        initComponents();
        int opciones = 2;
        switch (opciones) {
            case 2:
                footer =  new Vista.footer2();
                
                break;
                case 3:
                footer = new Vista.footer3();
                break;
            case 4:
                footer = new Vista.footer4();
                break;
            case 6:
                footer = new Vista.footer6();
                break;
        }
        
        
        jPanel1.add(footer);
        footer.setBounds(0, 590, 1000, 115);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footer21 = new Vista.footer2();
        footer22 = new Vista.footer2();
        jPanel1 = new javax.swing.JPanel();
        footer23 = new Vista.footer2();
        Foto = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        cabecera1 = new Vista.Cabecera();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);
        jPanel1.add(footer23);
        footer23.setBounds(0, 590, 1000, 103);

        Foto.setText("jLabel1");
        jPanel1.add(Foto);
        Foto.setBounds(10, 210, 440, 380);

        Texto.setText("Texto");
        jPanel1.add(Texto);
        Texto.setBounds(460, 210, 500, 380);
        jPanel1.add(cabecera1);
        cabecera1.setBounds(0, 0, 1000, 250);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fondoEscenas.jpg"))); // NOI18N
        fondo.setText("jLabel1");
        jPanel1.add(fondo);
        fondo.setBounds(0, 0, 1000, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escena_Completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escena_Completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escena_Completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escena_Completa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escena_Completa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Texto;
    private Vista.Cabecera cabecera1;
    private javax.swing.JLabel fondo;
    private Vista.footer2 footer21;
    private Vista.footer2 footer22;
    private Vista.footer2 footer23;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
