/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Mascarada.Opcion;
import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Alumno
 */
public class footer4 extends javax.swing.JPanel {
     ImageIcon botonRojo1=new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo1-4.png"));
    ImageIcon botonRojo2=new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo2-4.png"));
    
    private Controlador controlador;
    private VistaEscena vista;
    private ArrayList<Opcion> opciones;

    
    /**
     * Creates new form footer2
     */
    public footer4(Controlador controlador, VistaEscena vista) {
        initComponents();
        this.controlador = controlador;
        this.vista = vista;
        this.opciones = controlador.getPartida().getEscena().getOpciones();
        
        opcion1.setRolloverEnabled(true);
        opcion1.setIcon(botonRojo1);
        opcion1.setPressedIcon(botonRojo2);
        opcion1.setText(opciones.get(0).getTexto());
        opcion1.setForeground(Color.white);
        opcion1.setBackground(Color.black);

        opcion2.setRolloverEnabled(true);
        opcion2.setIcon(botonRojo1);
        opcion2.setPressedIcon(botonRojo2);
        opcion2.setText(opciones.get(1).getTexto());
        opcion2.setForeground(Color.white);
        opcion2.setBackground(Color.black);
        
        opcion3.setRolloverEnabled(true);
        opcion3.setIcon(botonRojo1);
        opcion3.setPressedIcon(botonRojo2);
        opcion3.setText(opciones.get(2).getTexto());
        opcion3.setForeground(Color.white);
        opcion3.setBackground(Color.black);
        
        opcion4.setRolloverEnabled(true);
        opcion4.setIcon(botonRojo1);
        opcion4.setPressedIcon(botonRojo2);
        opcion4.setText(opciones.get(3).getTexto());
        opcion4.setForeground(Color.white);
        opcion4.setBackground(Color.black);

        
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion1 = new javax.swing.JButton();
        opcion2 = new javax.swing.JButton();
        opcion3 = new javax.swing.JButton();
        opcion4 = new javax.swing.JButton();

        setOpaque(false);

        opcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Rojo1-4.png"))); // NOI18N
        opcion1.setText("jButton1");
        opcion1.setBorder(null);
        opcion1.setBorderPainted(false);
        opcion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion1MouseClicked(evt);
            }
        });

        opcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Rojo1-4.png"))); // NOI18N
        opcion2.setText("jButton1");
        opcion2.setBorderPainted(false);
        opcion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion2MouseClicked(evt);
            }
        });

        opcion3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Rojo1-4.png"))); // NOI18N
        opcion3.setText("jButton1");
        opcion3.setBorder(null);
        opcion3.setBorderPainted(false);
        opcion3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion3MouseClicked(evt);
            }
        });

        opcion4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Rojo1-4.png"))); // NOI18N
        opcion4.setText("jButton1");
        opcion4.setBorder(null);
        opcion4.setBorderPainted(false);
        opcion4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion1MouseClicked

         try {
             // TODO add your handling code here:
             controlador.escoger(opciones.get(0));
             vista.dispose();
         } catch (IOException ex) {
             Logger.getLogger(footer4.class.getName()).log(Level.SEVERE, null, ex);
         }             
    }//GEN-LAST:event_opcion1MouseClicked

    private void opcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion2MouseClicked

         try {
             // TODO add your handling code here:
             controlador.escoger(opciones.get(1));
             vista.dispose();
         } catch (IOException ex) {
             Logger.getLogger(footer4.class.getName()).log(Level.SEVERE, null, ex);
         }      
    }//GEN-LAST:event_opcion2MouseClicked

    private void opcion3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion3MouseClicked

         try {
             // TODO add your handling code here:
             controlador.escoger(opciones.get(2));
             vista.dispose();
         } catch (IOException ex) {
             Logger.getLogger(footer4.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_opcion3MouseClicked

    private void opcion4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion4MouseClicked

         try {
             // TODO add your handling code here:
             controlador.escoger(opciones.get(3));
             vista.dispose();
         } catch (IOException ex) {
             Logger.getLogger(footer4.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_opcion4MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton opcion1;
    private javax.swing.JButton opcion2;
    private javax.swing.JButton opcion3;
    private javax.swing.JButton opcion4;
    // End of variables declaration//GEN-END:variables
}
