/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Mascarada.Opcion;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Alumno
 */
public class footer2 extends javax.swing.JPanel{
    
    
    ImageIcon botonRojo1=new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo1.png"));
    ImageIcon botonRojo2=new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo2.png"));
    

    private ArrayList<JButton> botones;
    /**
     * Creates new form footer2
     */
    public footer2() {
        initComponents();
        opcion1.setRolloverEnabled(true);
        opcion2.setRolloverEnabled(true);
        opcion2.setIcon(botonRojo1);
        opcion2.setPressedIcon(botonRojo2);
        
        
        
    }
    
    public void setOpciones(ArrayList <Opcion> opciones){
         botones = new ArrayList<>();
        botones.add(opcion1);
        botones.add(opcion2);
        for (int i = 0; i < botones.size(); i++) {
            botones.get(i).setText(opciones.get(i).getTexto());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion1 = new javax.swing.JButton();
        opcion2 = new javax.swing.JButton();

        setOpaque(false);

        opcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo1.png"))); // NOI18N
        opcion1.setBorderPainted(false);
        opcion1.setContentAreaFilled(false);
        opcion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opcion1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion1MouseClicked(evt);
            }
        });

        opcion2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rojo1.png"))); // NOI18N
        opcion2.setBorderPainted(false);
        opcion2.setContentAreaFilled(false);
        opcion2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opcion2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        opcion2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        opcion2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        opcion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opcion2MouseEntered(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                opcion2MouseReleased(evt);
            }
        });
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcion2)
                    .addComponent(opcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion2MouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_opcion2MouseClicked

    private void opcion2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion2MouseReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_opcion2MouseReleased

    private void opcion2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion2MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opcion2MouseEntered

    private void opcion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opcion1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton opcion1;
    private javax.swing.JButton opcion2;
    // End of variables declaration//GEN-END:variables
}
