/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Mascarada.Clan;
import Controlador.Controlador;
import java.awt.Color;
import java.awt.List;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import jdk.jfr.Event;

/**
 *
 * @author Moru
 */
public class Inicio extends javax.swing.JFrame {

    private Controlador controlador;

    private ArrayList<Clan> clanes;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        //Elementos del Jlist
        //Elemento que me trae la info
        controlador = new Controlador();
        //Lista de la informacion de los clanes
        clanes = controlador.getListaClanes();
        //ArrayList para el Jlist
        DefaultListModel modelo = new DefaultListModel();
        //Traigo los nombres de los clanes al Jlist gracias a controlador y los seteo con el modelo

        for (int i = 0; i < clanes.size(); i++) {
            modelo.addElement(clanes.get(i).getNombre());

        }
        ListaClanes1.setModel(modelo);
        //Elementos de 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoTotal = new javax.swing.JPanel();
        TabbedMain = new javax.swing.JTabbedPane();
        CrearPartida = new javax.swing.JPanel();
        LabelClanes = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        Labeldificultad = new javax.swing.JLabel();
        BoxDificultad = new javax.swing.JComboBox<>();
        Crear = new javax.swing.JButton();
        Eleccion = new javax.swing.JScrollPane();
        ListaClanes1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionClan = new javax.swing.JTextPane();
        Habilidad1 = new javax.swing.JCheckBox();
        Habilidad2 = new javax.swing.JCheckBox();
        Habilidad3 = new javax.swing.JCheckBox();
        Habilidad4 = new javax.swing.JCheckBox();
        CargarPartida = new javax.swing.JPanel();
        PanelSeccionPartida = new javax.swing.JPanel();
        LabelFoto = new javax.swing.JLabel();
        Habilidad1Carga = new javax.swing.JLabel();
        Habilidad2Carga = new javax.swing.JLabel();
        ClanCarga = new javax.swing.JLabel();
        HoraCarga = new javax.swing.JLabel();
        BarraProgresoCarga = new javax.swing.JProgressBar();
        ProgresoCarga = new javax.swing.JLabel();
        NombreCarga = new javax.swing.JLabel();
        Foto = new javax.swing.JLabel();
        PanelSeccionPartida1 = new javax.swing.JPanel();
        LabelFoto1 = new javax.swing.JLabel();
        Habilidad1Carga1 = new javax.swing.JLabel();
        Habilidad2Carga1 = new javax.swing.JLabel();
        ClanCarga1 = new javax.swing.JLabel();
        HoraCarga1 = new javax.swing.JLabel();
        BarraProgresoCarga1 = new javax.swing.JProgressBar();
        ProgresoCarga1 = new javax.swing.JLabel();
        NombreCarga1 = new javax.swing.JLabel();
        Foto1 = new javax.swing.JLabel();
        PanelSeccionPartida2 = new javax.swing.JPanel();
        LabelFoto2 = new javax.swing.JLabel();
        Habilidad1Carga2 = new javax.swing.JLabel();
        Habilidad2Carga2 = new javax.swing.JLabel();
        ClanCarga2 = new javax.swing.JLabel();
        HoraCarga2 = new javax.swing.JLabel();
        BarraProgresoCarga2 = new javax.swing.JProgressBar();
        ProgresoCarga2 = new javax.swing.JLabel();
        NombreCarga2 = new javax.swing.JLabel();
        Foto2 = new javax.swing.JLabel();
        BorrarPartida = new javax.swing.JPanel();
        PanelSeccionPartida3 = new javax.swing.JPanel();
        LabelFoto3 = new javax.swing.JLabel();
        Habilidad1Carga3 = new javax.swing.JLabel();
        Habilidad2Carga3 = new javax.swing.JLabel();
        ClanCarga3 = new javax.swing.JLabel();
        HoraCarga3 = new javax.swing.JLabel();
        BarraProgresoCarga3 = new javax.swing.JProgressBar();
        ProgresoCarga3 = new javax.swing.JLabel();
        NombreCarga3 = new javax.swing.JLabel();
        Foto3 = new javax.swing.JLabel();
        Borrar = new javax.swing.JButton();
        PanelSeccionPartida4 = new javax.swing.JPanel();
        LabelFoto4 = new javax.swing.JLabel();
        Habilidad1Carga4 = new javax.swing.JLabel();
        Habilidad2Carga4 = new javax.swing.JLabel();
        ClanCarga4 = new javax.swing.JLabel();
        HoraCarga4 = new javax.swing.JLabel();
        BarraProgresoCarga4 = new javax.swing.JProgressBar();
        ProgresoCarga4 = new javax.swing.JLabel();
        NombreCarga4 = new javax.swing.JLabel();
        Foto4 = new javax.swing.JLabel();
        Borrar1 = new javax.swing.JButton();
        PanelSeccionPartida5 = new javax.swing.JPanel();
        LabelFoto5 = new javax.swing.JLabel();
        Habilidad1Carga5 = new javax.swing.JLabel();
        Habilidad2Carga5 = new javax.swing.JLabel();
        ClanCarga5 = new javax.swing.JLabel();
        HoraCarga5 = new javax.swing.JLabel();
        BarraProgresoCarga5 = new javax.swing.JProgressBar();
        ProgresoCarga5 = new javax.swing.JLabel();
        NombreCarga5 = new javax.swing.JLabel();
        Foto5 = new javax.swing.JLabel();
        Borrar2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelClanes.setText("Seleccione un clan:");

        labelNombre.setText("introduzca un nombre");

        TextNombre.setText("nombre......");
        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });

        Labeldificultad.setText("Seleccione la dificultad");

        BoxDificultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Facil", "Normal", "Dificil", "Pesadilla" }));
        BoxDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDificultadActionPerformed(evt);
            }
        });

        Crear.setText("Crear");
        Crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearMouseClicked(evt);
            }
        });
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        ListaClanes1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Brujah", "Ventru", "Tremere", "Nosferatu" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaClanes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaClanes1MouseClicked(evt);
            }
        });
        ListaClanes1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaClanes1ValueChanged(evt);
            }
        });
        Eleccion.setViewportView(ListaClanes1);

        jScrollPane1.setViewportView(DescripcionClan);

        Habilidad1.setText("jCheckBox1");

        Habilidad2.setText("jCheckBox1");

        Habilidad3.setText("jCheckBox1");

        Habilidad4.setText("jCheckBox1");

        javax.swing.GroupLayout CrearPartidaLayout = new javax.swing.GroupLayout(CrearPartida);
        CrearPartida.setLayout(CrearPartidaLayout);
        CrearPartidaLayout.setHorizontalGroup(
            CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGroup(CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearPartidaLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(CrearPartidaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CrearPartidaLayout.createSequentialGroup()
                            .addGap(280, 280, 280)
                            .addComponent(BoxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addComponent(Eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelClanes, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGap(353, 353, 353)
                .addComponent(Labeldificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Habilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(Habilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(Habilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(Habilidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearPartidaLayout.setVerticalGroup(
            CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearPartidaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(LabelClanes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Eleccion)
                    .addComponent(jScrollPane1))
                .addGap(39, 39, 39)
                .addGroup(CrearPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Habilidad1)
                    .addComponent(Habilidad2)
                    .addComponent(Habilidad3)
                    .addComponent(Habilidad4))
                .addGap(42, 42, 42)
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Labeldificultad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BoxDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Crear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        TabbedMain.addTab("Crear Partida", CrearPartida);

        PanelSeccionPartida.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto.setText("Foto");

        Habilidad1Carga.setText("Habilidad 1");

        Habilidad2Carga.setText("Habilidad 2");

        ClanCarga.setText("Clan");

        HoraCarga.setText("Hora");

        ProgresoCarga.setText("Progreso");

        NombreCarga.setText("Nombre");

        Foto.setText("retrato");

        javax.swing.GroupLayout PanelSeccionPartidaLayout = new javax.swing.GroupLayout(PanelSeccionPartida);
        PanelSeccionPartida.setLayout(PanelSeccionPartidaLayout);
        PanelSeccionPartidaLayout.setHorizontalGroup(
            PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                        .addGroup(PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                        .addComponent(ProgresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        PanelSeccionPartidaLayout.setVerticalGroup(
            PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartidaLayout.createSequentialGroup()
                        .addGroup(PanelSeccionPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 44, Short.MAX_VALUE))
        );

        PanelSeccionPartida1.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto1.setText("Foto");

        Habilidad1Carga1.setText("Habilidad 1");

        Habilidad2Carga1.setText("Habilidad 2");

        ClanCarga1.setText("Clan");

        HoraCarga1.setText("Hora");

        ProgresoCarga1.setText("Progreso");

        NombreCarga1.setText("Nombre");

        Foto1.setText("retrato");

        javax.swing.GroupLayout PanelSeccionPartida1Layout = new javax.swing.GroupLayout(PanelSeccionPartida1);
        PanelSeccionPartida1.setLayout(PanelSeccionPartida1Layout);
        PanelSeccionPartida1Layout.setHorizontalGroup(
            PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                        .addComponent(ProgresoCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        PanelSeccionPartida1Layout.setVerticalGroup(
            PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartida1Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 32, Short.MAX_VALUE))
        );

        PanelSeccionPartida2.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto2.setText("Foto");

        Habilidad1Carga2.setText("Habilidad 1");

        Habilidad2Carga2.setText("Habilidad 2");

        ClanCarga2.setText("Clan");

        HoraCarga2.setText("Hora");

        ProgresoCarga2.setText("Progreso");

        NombreCarga2.setText("Nombre");

        Foto2.setText("retrato");

        javax.swing.GroupLayout PanelSeccionPartida2Layout = new javax.swing.GroupLayout(PanelSeccionPartida2);
        PanelSeccionPartida2.setLayout(PanelSeccionPartida2Layout);
        PanelSeccionPartida2Layout.setHorizontalGroup(
            PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                        .addComponent(ProgresoCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
        );
        PanelSeccionPartida2Layout.setVerticalGroup(
            PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartida2Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CargarPartidaLayout = new javax.swing.GroupLayout(CargarPartida);
        CargarPartida.setLayout(CargarPartidaLayout);
        CargarPartidaLayout.setHorizontalGroup(
            CargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargarPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelSeccionPartida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSeccionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(CargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CargarPartidaLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(PanelSeccionPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
        CargarPartidaLayout.setVerticalGroup(
            CargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CargarPartidaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(PanelSeccionPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(PanelSeccionPartida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(CargarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(CargarPartidaLayout.createSequentialGroup()
                    .addGap(244, 244, 244)
                    .addComponent(PanelSeccionPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(245, Short.MAX_VALUE)))
        );

        TabbedMain.addTab("Cargar Partida", CargarPartida);

        PanelSeccionPartida3.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto3.setText("Foto");

        Habilidad1Carga3.setText("Habilidad 1");

        Habilidad2Carga3.setText("Habilidad 2");

        ClanCarga3.setText("Clan");

        HoraCarga3.setText("Hora");

        ProgresoCarga3.setText("Progreso");

        NombreCarga3.setText("Nombre");

        Foto3.setText("retrato");

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSeccionPartida3Layout = new javax.swing.GroupLayout(PanelSeccionPartida3);
        PanelSeccionPartida3.setLayout(PanelSeccionPartida3Layout);
        PanelSeccionPartida3Layout.setHorizontalGroup(
            PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                        .addComponent(ProgresoCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(Borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSeccionPartida3Layout.setVerticalGroup(
            PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartida3Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Borrar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelSeccionPartida4.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto4.setText("Foto");

        Habilidad1Carga4.setText("Habilidad 1");

        Habilidad2Carga4.setText("Habilidad 2");

        ClanCarga4.setText("Clan");

        HoraCarga4.setText("Hora");

        ProgresoCarga4.setText("Progreso");

        NombreCarga4.setText("Nombre");

        Foto4.setText("retrato");

        Borrar1.setText("Borrar");
        Borrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSeccionPartida4Layout = new javax.swing.GroupLayout(PanelSeccionPartida4);
        PanelSeccionPartida4.setLayout(PanelSeccionPartida4Layout);
        PanelSeccionPartida4Layout.setHorizontalGroup(
            PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto4, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                        .addComponent(ProgresoCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(Borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSeccionPartida4Layout.setVerticalGroup(
            PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartida4Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Borrar1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        PanelSeccionPartida5.setBackground(new java.awt.Color(51, 51, 51));

        LabelFoto5.setText("Foto");

        Habilidad1Carga5.setText("Habilidad 1");

        Habilidad2Carga5.setText("Habilidad 2");

        ClanCarga5.setText("Clan");

        HoraCarga5.setText("Hora");

        ProgresoCarga5.setText("Progreso");

        NombreCarga5.setText("Nombre");

        Foto5.setText("retrato");

        Borrar2.setText("Borrar");
        Borrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Borrar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSeccionPartida5Layout = new javax.swing.GroupLayout(PanelSeccionPartida5);
        PanelSeccionPartida5.setLayout(PanelSeccionPartida5Layout);
        PanelSeccionPartida5Layout.setHorizontalGroup(
            PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Habilidad2Carga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Habilidad1Carga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(195, 195, 195)
                .addGroup(PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HoraCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BarraProgresoCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClanCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(Foto5, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                        .addComponent(ProgresoCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33))
            .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(Borrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelSeccionPartida5Layout.setVerticalGroup(
            PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(NombreCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Habilidad1Carga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Habilidad2Carga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Foto5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelSeccionPartida5Layout.createSequentialGroup()
                        .addGroup(PanelSeccionPartida5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProgresoCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelFoto5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BarraProgresoCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClanCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HoraCarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Borrar2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BorrarPartidaLayout = new javax.swing.GroupLayout(BorrarPartida);
        BorrarPartida.setLayout(BorrarPartidaLayout);
        BorrarPartidaLayout.setHorizontalGroup(
            BorrarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BorrarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSeccionPartida5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelSeccionPartida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BorrarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BorrarPartidaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelSeccionPartida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BorrarPartidaLayout.setVerticalGroup(
            BorrarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrarPartidaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(PanelSeccionPartida3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(PanelSeccionPartida5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(BorrarPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BorrarPartidaLayout.createSequentialGroup()
                    .addGap(238, 238, 238)
                    .addComponent(PanelSeccionPartida4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(227, Short.MAX_VALUE)))
        );

        TabbedMain.addTab("Borrar Partida", BorrarPartida);

        javax.swing.GroupLayout FondoTotalLayout = new javax.swing.GroupLayout(FondoTotal);
        FondoTotal.setLayout(FondoTotalLayout);
        FondoTotalLayout.setHorizontalGroup(
            FondoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedMain)
        );
        FondoTotalLayout.setVerticalGroup(
            FondoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedMain)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void BoxDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDificultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDificultadActionPerformed

    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearActionPerformed

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BorrarActionPerformed

    private void Borrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Borrar1ActionPerformed

    private void Borrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Borrar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Borrar2ActionPerformed

    private void ListaClanes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClanes1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ListaClanes1MouseClicked

    private void ListaClanes1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaClanes1ValueChanged

        // TODO add your handling code here:
        Clan clan;
        String nombreClan = ListaClanes1.getSelectedValue();
        int contador=0;
        HashMap<String, Boolean>habilidades ;
                Iterator<String> it ;
                String[]nombres=new String[4];
        for (int i = 0; i < clanes.size(); i++) {
            clan = clanes.get(i);
            if (clan.getNombre().equalsIgnoreCase(nombreClan)) {
                DescripcionClan.setText(clanes.get(i).getDescripcion());
                habilidades = clan.getHabilidades();
                it = habilidades.keySet().iterator();

                while (it.hasNext()) {
                    String nombreHabilidad = it.next();
                    nombres[contador]=nombreHabilidad;
                    contador++;
                   
                }
                

            }
        }Habilidad1.setText(nombres[0]);
        Habilidad2.setText(nombres[1]);
        Habilidad3.setText(nombres[2]);
        Habilidad4.setText(nombres[3]);
        

    }//GEN-LAST:event_ListaClanes1ValueChanged

    private void CrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearMouseClicked
        // TODO add your handling code here:

        if (controlador.comprobarNombrePersonaje(TextNombre.getText())) {

        } else {
            TextNombre.setBackground(Color.red);
        }


    }//GEN-LAST:event_CrearMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar BarraProgresoCarga;
    private javax.swing.JProgressBar BarraProgresoCarga1;
    private javax.swing.JProgressBar BarraProgresoCarga2;
    private javax.swing.JProgressBar BarraProgresoCarga3;
    private javax.swing.JProgressBar BarraProgresoCarga4;
    private javax.swing.JProgressBar BarraProgresoCarga5;
    private javax.swing.JButton Borrar;
    private javax.swing.JButton Borrar1;
    private javax.swing.JButton Borrar2;
    private javax.swing.JPanel BorrarPartida;
    private javax.swing.JComboBox<String> BoxDificultad;
    private javax.swing.JPanel CargarPartida;
    private javax.swing.JLabel ClanCarga;
    private javax.swing.JLabel ClanCarga1;
    private javax.swing.JLabel ClanCarga2;
    private javax.swing.JLabel ClanCarga3;
    private javax.swing.JLabel ClanCarga4;
    private javax.swing.JLabel ClanCarga5;
    private javax.swing.JButton Crear;
    private javax.swing.JPanel CrearPartida;
    private javax.swing.JTextPane DescripcionClan;
    private javax.swing.JScrollPane Eleccion;
    private javax.swing.JPanel FondoTotal;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Foto1;
    private javax.swing.JLabel Foto2;
    private javax.swing.JLabel Foto3;
    private javax.swing.JLabel Foto4;
    private javax.swing.JLabel Foto5;
    private javax.swing.JCheckBox Habilidad1;
    private javax.swing.JLabel Habilidad1Carga;
    private javax.swing.JLabel Habilidad1Carga1;
    private javax.swing.JLabel Habilidad1Carga2;
    private javax.swing.JLabel Habilidad1Carga3;
    private javax.swing.JLabel Habilidad1Carga4;
    private javax.swing.JLabel Habilidad1Carga5;
    private javax.swing.JCheckBox Habilidad2;
    private javax.swing.JLabel Habilidad2Carga;
    private javax.swing.JLabel Habilidad2Carga1;
    private javax.swing.JLabel Habilidad2Carga2;
    private javax.swing.JLabel Habilidad2Carga3;
    private javax.swing.JLabel Habilidad2Carga4;
    private javax.swing.JLabel Habilidad2Carga5;
    private javax.swing.JCheckBox Habilidad3;
    private javax.swing.JCheckBox Habilidad4;
    private javax.swing.JLabel HoraCarga;
    private javax.swing.JLabel HoraCarga1;
    private javax.swing.JLabel HoraCarga2;
    private javax.swing.JLabel HoraCarga3;
    private javax.swing.JLabel HoraCarga4;
    private javax.swing.JLabel HoraCarga5;
    private javax.swing.JLabel LabelClanes;
    private javax.swing.JLabel LabelFoto;
    private javax.swing.JLabel LabelFoto1;
    private javax.swing.JLabel LabelFoto2;
    private javax.swing.JLabel LabelFoto3;
    private javax.swing.JLabel LabelFoto4;
    private javax.swing.JLabel LabelFoto5;
    private javax.swing.JLabel Labeldificultad;
    private javax.swing.JList<String> ListaClanes1;
    private javax.swing.JLabel NombreCarga;
    private javax.swing.JLabel NombreCarga1;
    private javax.swing.JLabel NombreCarga2;
    private javax.swing.JLabel NombreCarga3;
    private javax.swing.JLabel NombreCarga4;
    private javax.swing.JLabel NombreCarga5;
    private javax.swing.JPanel PanelSeccionPartida;
    private javax.swing.JPanel PanelSeccionPartida1;
    private javax.swing.JPanel PanelSeccionPartida2;
    private javax.swing.JPanel PanelSeccionPartida3;
    private javax.swing.JPanel PanelSeccionPartida4;
    private javax.swing.JPanel PanelSeccionPartida5;
    private javax.swing.JLabel ProgresoCarga;
    private javax.swing.JLabel ProgresoCarga1;
    private javax.swing.JLabel ProgresoCarga2;
    private javax.swing.JLabel ProgresoCarga3;
    private javax.swing.JLabel ProgresoCarga4;
    private javax.swing.JLabel ProgresoCarga5;
    private javax.swing.JTabbedPane TabbedMain;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombre;
    // End of variables declaration//GEN-END:variables
}
