/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Mascarada.Util;
import java.awt.Color;

/**
 *
 * @author Alumno
 */
public class Mapa extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    public Mapa() {
        initComponents();
        Util.centrar(this);
        
        callejon.setText("Callejon");
        callejon.setForeground(Color.white);
        callejon.setBackground(Color.black);
         
        biblioteca .setText("Biblioteca");
        biblioteca.setForeground(Color.white);
        biblioteca.setBackground(Color.black);
        
        entrada.setText("Entrada pueblo");
        entrada.setForeground(Color.white);
        entrada.setBackground(Color.black);
        
        colina.setText("Casa colina");
        colina.setForeground(Color.white);
        colina.setBackground(Color.black);
        
        periodicofuera.setText("Periodico fuera");
        periodicofuera.setForeground(Color.white);
        periodicofuera.setBackground(Color.black);
        
        casaabandonada.setText("Casa abandonada");
        casaabandonada.setForeground(Color.white);
        casaabandonada.setBackground(Color.black);
        
        pub1.setText("Pub 1");
        pub1.setForeground(Color.white);
        pub1.setBackground(Color.black);
        
        periodicoDentro.setText("Periodico dentro");
        periodicoDentro.setForeground(Color.white);
        periodicoDentro.setBackground(Color.black);
        
        callejonTienda.setText("Callejon tienda");
        callejonTienda.setForeground(Color.white);
        callejonTienda.setBackground(Color.black);
        
        pub2.setText("Pub 2");
        pub2.setForeground(Color.white);
        pub2.setBackground(Color.black);
        
        puertaIglesia.setText("Puerta iglesia");
        puertaIglesia.setForeground(Color.white);
        puertaIglesia.setBackground(Color.black);
        
        plazaCentral.setText("Plaza central");
        plazaCentral.setForeground(Color.white);
        plazaCentral.setBackground(Color.black);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        callejon = new javax.swing.JButton();
        biblioteca = new javax.swing.JButton();
        entrada = new javax.swing.JButton();
        colina = new javax.swing.JButton();
        periodicofuera = new javax.swing.JButton();
        casaabandonada = new javax.swing.JButton();
        pub1 = new javax.swing.JButton();
        periodicoDentro = new javax.swing.JButton();
        callejonTienda = new javax.swing.JButton();
        pub2 = new javax.swing.JButton();
        puertaIglesia = new javax.swing.JButton();
        plazaCentral = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        callejon.setText("Callejon");
        jPanel1.add(callejon);
        callejon.setBounds(690, 650, 80, 40);

        biblioteca.setText("Biblioteca");
        jPanel1.add(biblioteca);
        biblioteca.setBounds(140, 210, 90, 50);

        entrada.setText("Entrada pueblo");
        jPanel1.add(entrada);
        entrada.setBounds(840, 110, 130, 40);

        colina.setText("Casa colina");
        jPanel1.add(colina);
        colina.setBounds(870, 550, 100, 40);

        periodicofuera.setText("Periodico Fuera");
        jPanel1.add(periodicofuera);
        periodicofuera.setBounds(190, 610, 120, 40);

        casaabandonada.setText("Casa abandonada");
        jPanel1.add(casaabandonada);
        casaabandonada.setBounds(860, 280, 130, 40);

        pub1.setText("Pub 1");
        jPanel1.add(pub1);
        pub1.setBounds(310, 100, 70, 40);

        periodicoDentro.setText("Periodico Dentro");
        jPanel1.add(periodicoDentro);
        periodicoDentro.setBounds(190, 560, 120, 40);

        callejonTienda.setText("Callejon tienda");
        jPanel1.add(callejonTienda);
        callejonTienda.setBounds(140, 470, 120, 40);

        pub2.setText("Pub 2");
        jPanel1.add(pub2);
        pub2.setBounds(790, 410, 80, 40);

        puertaIglesia.setText("Puerta iglesia");
        jPanel1.add(puertaIglesia);
        puertaIglesia.setBounds(90, 360, 120, 40);

        plazaCentral.setText("Plaza central");
        jPanel1.add(plazaCentral);
        plazaCentral.setBounds(550, 420, 120, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/mapa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mapa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton biblioteca;
    private javax.swing.JButton callejon;
    private javax.swing.JButton callejonTienda;
    private javax.swing.JButton casaabandonada;
    private javax.swing.JButton colina;
    private javax.swing.JButton entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton periodicoDentro;
    private javax.swing.JButton periodicofuera;
    private javax.swing.JButton plazaCentral;
    private javax.swing.JButton pub1;
    private javax.swing.JButton pub2;
    private javax.swing.JButton puertaIglesia;
    // End of variables declaration//GEN-END:variables
}
