/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Mascarada.Equipo;
import Mascarada.Partida;
import Mascarada.Persona;
import Mascarada.Util;
import Mascarada.Vampire;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Moru
 */
public class VistaFicha extends javax.swing.JFrame {
    
    private Partida partida;
    private ArrayList<Equipo> equipo;

    /**
     * Creates new form FichaAuspex
     */
    public VistaFicha(Persona p) throws IOException {
        if (p instanceof Vampire){
            Vampire v = (Vampire) p;
        }
        
        if(p.getEstadoDeAnimo()==Util.EA_PROTAGONISTA){
            //mostramos lo del protagonista
            //listas seleccionables
            //boton de guardar
        } else {
            //listas NOOOOOO seleccionables
            //label de estado de ánimo
        }
        initComponents();
        this.partida = partida;
        //Lista de la informacion de los clanes
        equipo = partida.getProtagonista().getEquipacion();
     
        DefaultListModel listaAtaque = new DefaultListModel();
        DefaultListModel listaAmuletos = new DefaultListModel();
        DefaultListModel listaDefensivos = new DefaultListModel();
        DefaultListModel listaEspeciales = new DefaultListModel();
        
         for (int i = 0; i < equipo.size(); i++) {
            listaAtaque.addElement(equipo.get(i).getNombre());
            listaAmuletos.addElement(equipo.get(i).getNombre());
            listaDefensivos.addElement(equipo.get(i).getNombre());
            listaEspeciales.addElement(equipo.get(i).getNombre());

        }
        this.listaAmuletos.setModel(listaAmuletos);
        this.listaAtaque.setModel(listaAtaque);
        this.listaDefensivos.setModel(listaDefensivos);
        this.listaEspecial.setModel(listaEspeciales);
        datosFichaAuspex(partida);
    }
     public void datosFichaAuspex( Partida partida){
        nombre.setText(partida.getProtagonista().getNombre());
        String[]hab1y2=partida.getProtagonista().getHabilidades().split(";");
        habilidad1.setText(hab1y2[0]);
        dineroDato.setText(hab1y2[1]);
        clan.setText(partida.getProtagonista().getClan().getNombre());
        dineroDato.setText(partida.getProtagonista().getDinero()+"");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        foto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        objetoEspecial = new javax.swing.JLabel();
        clan = new javax.swing.JLabel();
        habilidad1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEspecial = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAtaque = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDefensivos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaAmuletos = new javax.swing.JList<>();
        amuletos = new javax.swing.JLabel();
        ataque = new javax.swing.JLabel();
        defensivo = new javax.swing.JLabel();
        dineroDato = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        habilidad3 = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ataqueDato = new javax.swing.JLabel();
        estadoAnimo1 = new javax.swing.JLabel();
        vida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        foto.setText("Foto");
        jPanel1.add(foto);
        foto.setBounds(10, 10, 180, 190);

        jLabel2.setText("Ataque");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 100, 110, 30);

        objetoEspecial.setText("Objetos Especiales");
        jPanel1.add(objetoEspecial);
        objetoEspecial.setBounds(800, 270, 120, 20);

        clan.setText("Clan");
        jPanel1.add(clan);
        clan.setBounds(230, 50, 120, 20);

        habilidad1.setText("Habilidad1");
        jPanel1.add(habilidad1);
        habilidad1.setBounds(230, 80, 120, 20);

        listaEspecial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaEspecial);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(770, 300, 200, 350);

        listaAtaque.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listaAtaque);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(30, 300, 200, 350);

        listaDefensivos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaDefensivos);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(270, 300, 200, 350);

        listaAmuletos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaAmuletos);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(520, 300, 200, 350);

        amuletos.setText("Amuletos");
        jPanel1.add(amuletos);
        amuletos.setBounds(560, 270, 120, 20);

        ataque.setText("Objetos de Ataque");
        jPanel1.add(ataque);
        ataque.setBounds(70, 270, 120, 20);

        defensivo.setText("Objetos Defensivos");
        jPanel1.add(defensivo);
        defensivo.setBounds(320, 270, 120, 20);
        jPanel1.add(dineroDato);
        dineroDato.setBounds(290, 150, 50, 20);

        nombre.setText("Nombre");
        jPanel1.add(nombre);
        nombre.setBounds(230, 20, 60, 20);

        habilidad3.setText("Habilidad2");
        jPanel1.add(habilidad3);
        habilidad3.setBounds(230, 110, 120, 20);

        dinero.setText("Dinero");
        jPanel1.add(dinero);
        dinero.setBounds(230, 150, 50, 20);

        jLabel3.setText("Estado de animo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 60, 110, 30);
        jPanel1.add(ataqueDato);
        ataqueDato.setBounds(570, 100, 110, 30);
        jPanel1.add(estadoAnimo1);
        estadoAnimo1.setBounds(580, 60, 110, 30);
        jPanel1.add(vida);
        vida.setBounds(580, 20, 110, 30);

        jLabel6.setText("Vida:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(420, 20, 110, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/fondoEscenas.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, 0, 1000, 700);

        jLabel4.setText("Ataque");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 100, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amuletos;
    private javax.swing.JLabel ataque;
    private javax.swing.JLabel ataqueDato;
    private javax.swing.JLabel clan;
    private javax.swing.JLabel defensivo;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel dineroDato;
    private javax.swing.JLabel estadoAnimo1;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel habilidad1;
    private javax.swing.JLabel habilidad3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaAmuletos;
    private javax.swing.JList<String> listaAtaque;
    private javax.swing.JList<String> listaDefensivos;
    private javax.swing.JList<String> listaEspecial;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel objetoEspecial;
    private javax.swing.JLabel vida;
    // End of variables declaration//GEN-END:variables
}
