package Vista;

import Controlador.Controlador;
import Mascarada.Util;
import java.awt.Color;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Vista para la conexión con la base de datos.
 *
 * @author Gonzalo López Fernández
 */
public class VistaConexionBD extends javax.swing.JFrame {

    private Controlador controlador;

    /**
     * Creates new form VistaConexionBD
     */
    public VistaConexionBD(Controlador controlador) throws IOException {
        initComponents();
        String[] config;
        this.controlador = controlador;
        Util.centrar(this);
        config = controlador.getConfiguracionBD().split(";");
        campoPuerto.setText(config[0]);
        campousuario.setText(config[2]);
        campoContraseña.setText(config[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        puerto = new javax.swing.JLabel();
        campoPuerto = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        campousuario = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        campoContraseña = new javax.swing.JPasswordField();
        botonConectar = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        panelText = new javax.swing.JScrollPane();
        panelTexto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        puerto.setBackground(new java.awt.Color(0, 0, 0));
        puerto.setForeground(new java.awt.Color(255, 255, 255));
        puerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        puerto.setText("Puerto");

        campoPuerto.setBackground(new java.awt.Color(0, 0, 0));
        campoPuerto.setForeground(new java.awt.Color(255, 255, 255));
        campoPuerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoPuerto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPuertoMouseClicked(evt);
            }
        });

        usuario.setBackground(new java.awt.Color(0, 0, 0));
        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("Usuario");

        campousuario.setBackground(new java.awt.Color(0, 0, 0));
        campousuario.setForeground(new java.awt.Color(255, 255, 255));
        campousuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campousuarioMouseClicked(evt);
            }
        });

        contraseña.setBackground(new java.awt.Color(0, 0, 0));
        contraseña.setForeground(new java.awt.Color(255, 255, 255));
        contraseña.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contraseña.setText("Contraseña");

        campoContraseña.setBackground(new java.awt.Color(0, 0, 0));
        campoContraseña.setForeground(new java.awt.Color(255, 255, 255));
        campoContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoContraseña.setText("jPasswordField1");
        campoContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContraseñaMouseClicked(evt);
            }
        });

        botonConectar.setBackground(new java.awt.Color(51, 51, 51));
        botonConectar.setForeground(new java.awt.Color(255, 255, 255));
        botonConectar.setText("Conectar");
        botonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarActionPerformed(evt);
            }
        });

        botonContinuar.setBackground(new java.awt.Color(51, 51, 51));
        botonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        panelTexto.setEditable(false);
        panelTexto.setBackground(new java.awt.Color(0, 0, 0));
        panelTexto.setColumns(20);
        panelTexto.setForeground(new java.awt.Color(255, 255, 255));
        panelTexto.setRows(5);
        panelTexto.setText("No se ha podido conectar con la base de datos \ncon los parámetros actuales.\nPor favor, introduzca los datos correctos.\nEn caso de no poder conectar continue sin \nrealizar la conexión, pero los datos de su partida\nserán solo locales, NUNCA estarán disponibles\nonline, ni en nigún otro ordenador.");
        panelTexto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        panelText.setViewportView(panelTexto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelText, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonContinuar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(campoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseña)
                            .addComponent(usuario)
                            .addComponent(puerto)
                            .addComponent(botonConectar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoContraseña, campoPuerto, campousuario, contraseña, puerto, usuario});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(puerto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonContinuar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarActionPerformed
        String url = campoPuerto.getText();
        String use = campousuario.getText();
        String pas = campoContraseña.getText();

        boolean conseguido = controlador.conectar(url, use, pas);
        if (conseguido) {
            try {
                new VistaCredenciales(controlador).setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(VistaConexionBD.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        } else {
            campoPuerto.setForeground(Color.red);
            campousuario.setForeground(Color.red);
            campoContraseña.setForeground(Color.red);
        }
    }//GEN-LAST:event_botonConectarActionPerformed

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContinuarActionPerformed
        try {
            new VistaPartidas(controlador, "Local").setVisible(true);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(VistaConexionBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_botonContinuarActionPerformed

    private void campoPuertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPuertoMouseClicked
        cambiarTextoABlanco();
    }//GEN-LAST:event_campoPuertoMouseClicked

    private void campousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campousuarioMouseClicked
        cambiarTextoABlanco();
    }//GEN-LAST:event_campousuarioMouseClicked

    private void campoContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraseñaMouseClicked
        cambiarTextoABlanco();
    }//GEN-LAST:event_campoContraseñaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaConexionBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaConexionBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaConexionBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaConexionBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //                   new VistaConexionBD().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConectar;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoPuerto;
    private javax.swing.JTextField campousuario;
    private javax.swing.JLabel contraseña;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane panelText;
    private javax.swing.JTextArea panelTexto;
    private javax.swing.JLabel puerto;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables

    private void cambiarTextoABlanco() {
        campoPuerto.setForeground(Color.WHITE);
        campousuario.setForeground(Color.WHITE);
        campoContraseña.setForeground(Color.WHITE);
    }

}
